version: "3.9"
services:
  backend:
    build:
      context: ./polygon-backend
    container_name: polygon-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - polygon-network
    volumes:
      - ./polygon-backend/uploads:/app/uploads

  frontend:
    build:
      context: ./polygon-mapper
    container_name: polygon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - polygon-network

  postgres:
    image: postgres:14
    container_name: polygon-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15maret2004
      POSTGRES_DB: region_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - polygon-network

networks:
  polygon-network:
    driver: bridge

volumes:
  postgres_data:
